on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  test-linux:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - 1.37.0
          - stable
          - beta
          - nightly
        mb_const_generics:
          - ""
          - "--features const-generics"
        exclude:
          - mb_const_generics: "--features const-generics"
            rust: 1.37.0
        include:
          - os: macos-latest
            rust: stable
          - os: windows-latest
            rust: stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --verbose --features "strict" ${{ matrix.mb_const_generics }}
      - run: cargo doc --features "strict" ${{ matrix.mb_const_generics }}

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      # Allow deprecated because we test the no_std feature.
      - run: cargo clippy --all-features -- -D warnings -A deprecated
